version: '2'
services:
  spark-master:
    image: bdubas/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./shared:/shared
  spark-worker-1:
    image: bdubas/spark-worker:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./shared:/shared
  web:
    image: bdubas/spark-submit:latest
    container_name: spark-submit
    depends_on:
      - spark-master
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/shared
